added incomplete transfer cleanup

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -10,11 +10,13 @@ safe_source $_dir/lib/all.sh
 
 s=$1
 d=$2
+dry_run=false
 
 [[ $(whoami) = "root" ]] || { sudo $0 $*; exit 0; }
 
 echo "from $s to $d"
-
+echo "==============================================="
+echo
 # source and destination should be on different disks
 require_different_disks $s $d
 
@@ -36,15 +38,32 @@ for _snap_root in $(get_snapshot_roots $s); do
     echo "--- already sent: ---"
     find_sent_subs "$src_mnt/$snap_root" "$dst_mnt/$snap_root"
 
+    echo "--- incomplete ---"
+    for incomplete in `list_subvol_below $dst_mnt/$snap_root/partial`; do
+        echo_yellow "Found incomplete snapshot: $incomplete"
+        if [[ $dry_run = false ]]; then
+            btrfs sub del $incomplete
+        fi
+    done
+
     echo "--- missing: ---"
     for missing in `find_missing_subs "$src_mnt/$snap_root" "$dst_mnt/$snap_root"`; do
         parent=$(find_prev_snap $missing "${snapshots[@]}")
-        if [[ -z $parent ]]; then
-            echo_red "No parent found, won't send whole snapshot"
-            continue
+        if [[ $dry_run = true ]]; then
+            [[ -z $parent ]] && msg="whole snap" || msg="@$(basename $parent)"
+            echo "will send $missing ($msg) -> $dst_mnt/$snap_root"
+        else
+            if [[ -z $parent ]]; then
+                echo_yellow "No parent found for $missing, sending whole snapshot"
+                _parent_arg=
+            else
+                _parent_arg="-p $parent"
+            fi
+            mkdir -p $dst_mnt/$snap_root/partial
+
+            btrfs send $_parent_arg $missing | pv | btrfs receive $dst_mnt/$snap_root/partial
+            [[ $? -eq 0 ]] && mv $dst_mnt/$snap_root/partial/$(basename $missing) $dst_mnt/$snap_root
         fi
-        mkdir -p $dst_mnt/$snap_root
-        echo btrfs send -p $parent $missing | pv | btrfs receive $dst_mnt/$snap_root/
     done
 done
 
